package model.views.staticvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Sep 20 12:19:57 IST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaticStatusVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StaticStatusVOImpl() {
    }
}

