package model.views.staticvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 25 20:03:21 IST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaticDocumentVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StaticDocumentVOImpl() {
    }
}

