package model.services;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Sep 18 14:26:58 IST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class PMAppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public PMAppModuleImpl() {
    }


    /**
     * Container's getter for Projects1.
     * @return Projects1
     */
    public ViewObjectImpl getProjects1() {
        return (ViewObjectImpl) findViewObject("Projects1");
    }
}

